"use client";
import {useMemo,useState} from "react";

type View="overview"|"data"|"employee"|"incentive"|"reports";
type Report="workshop"|"breakdown"|"claims"|"customer";

const kras=[
 ["Technical Knowledge",[3,3,3,3]],
 ["Kaam Sekhne ki koshish",[4,4,2,4]],
 ["Bay Cleanliness",[4,4,3,3]],
 ["Uniform",[5,5,2,5]],
 ["Punctuality - Time par aana",[4,4,3,4]],
 ["Repeat job nahin aana",[3,3,3,4]],
] as const;
const weekly=[3.833333,3.833333,2.666667,3.833333];
const sources=[
 ["June 26.xlsx","KRA Assessment Mechanic · Incentive · Service advisor · CRE","Employee evaluation & incentive"],
 ["Gazipur workshop reporting Jul 26.xlsx","Job Card · Daily Report · Spare Part · Inventory Check","Workshop & commercial reporting"],
 ["Breakdown tracking.xlsx","Daily service Tracker","Breakdown reporting"],
 ["AMIT UPDATED FML Claim Sheet Feb 26.xlsx","Data Report sheet","FML / claim reporting"],
];
const workshop=[["91","Lachchiram PG College Salikpur Gzp","9454277263","UP61AT2335","T1","Paid","₹410","₹200","₹646"],["92","Samta Pb School","9454277363","UP61AT0416","T1","Paid","₹160","₹1,750","₹2,225"]];
const breakdown=[["—","UP61CT3221","M/s. ASHA MAHAVIDYALAYA","FUEL METER IS NOT SHOWIN","35","Open","—"]];
const claims=[["WCI25C000102","356","27-Mar-2025","₹2,765","Warranty","Accepted","₹2,765","NOT FOUND","05-Jun-2025"],["WCI25C000103","357","27-Mar-2025","₹2,588","Warranty","Accepted","₹2,588","NOT FOUND","05-Jun-2025"],["WCI26C000001","358","30-Apr-2025","₹1,465","Warranty","REJECTED","₹0","₹1,464.91","29-May-2025"],["WCI26C000002","359","30-Apr-2025","₹2,187","Warranty","Accepted","₹2,186.85","0","29-May-2025"]];

function Badge({children,tone="source"}:{children:React.ReactNode;tone?:"source"|"derived"|"proposed"|"neutral"}){return <span className={`badge ${tone}`}>{children}</span>}
function Card({children}:{children:React.ReactNode}){return <section className="panel">{children}</section>}
function Head({title,sub,tag}:{title:string;sub?:string;tag?:string}){return <div className="panel-head"><div><h3>{title}</h3>{sub&&<p>{sub}</p>}</div>{tag&&<Badge tone="neutral">{tag}</Badge>}</div>}
function Table({headers,rows}:{headers:string[];rows:string[][]}){return <div className="table-panel"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{j===0?<b>{v}</b>:v}</td>)}</tr>)}</tbody></table></div>}
function Metric({label,value,note}:{label:string;value:string;note:string}){return <div className="stat"><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}

export default function Home(){
 const [view,setView]=useState<View>("overview");
 const [tab,setTab]=useState<"evaluation"|"history"|"performance">("evaluation");
 const [week,setWeek]=useState(1); const [report,setReport]=useState<Report>("workshop");
 const monthly=useMemo(()=>weekly.reduce((a,b)=>a+b,0)/weekly.length,[]);
 const nav:[[View,string],[View,string],[View,string],[View,string],[View,string]]=[["overview","Overview"],["data","Data Hub"],["employee","Employee Intelligence"],["incentive","Incentive"],["reports","Data & Reports"]];
 return <main className="app-shell">
  <aside className="sidebar"><div className="brand"><div className="brand-mark">D</div><div><b>Dealer Intelligence</b><span>Management platform</span></div></div><div className="source-note"><span className="badge">GHAZIPUR</span><span>Force Motors workshop</span></div><div className="nav-label">WORKSPACE</div>{nav.map(([id,label])=><button key={id} className={`nav-item ${view===id?"active":""}`} onClick={()=>setView(id)}><i className="nav-dot"/>{label}</button>)}<div className="nav-label">DATA SOURCES</div><button className="nav-item" onClick={()=>setView("data")}><i className="nav-dot"/>4 workbooks imported</button><div className="sidebar-bottom"><Badge tone="neutral">STATIC DEMO</Badge><b>Source · Derived · Proposed</b>Prototype uses the supplied dealership reporting structure.</div></aside>
  <section className="content"><header className="topbar"><div><div className="crumb">DEALER INTELLIGENCE / GHAZIPUR</div><h1>{nav.find(n=>n[0]===view)?.[1]}</h1></div><div className="top-actions"><button>June 2026⌄</button><button>Export preview</button></div></header><div className="page">
   {view==="overview"&&<Overview setView={setView} monthly={monthly}/>} {view==="data"&&<DataHub/>} {view==="employee"&&<Employee tab={tab} setTab={setTab} week={week} setWeek={setWeek} monthly={monthly}/>} {view==="incentive"&&<Incentive/>} {view==="reports"&&<Reports report={report} setReport={setReport}/>} 
  </div></section></main>
}

function Overview({setView,montly:unused,monthly}:{setView:(v:View)=>void;montly?:number;monthly:number}){return <>
 <div className="intro"><div><Badge tone="neutral">THE PRODUCT</Badge><h2>From scattered reports to one management layer.</h2><p>Force / Zoho can remain the operational systems. This layer brings the dealership's existing Excel reporting, employee evaluation, incentives, breakdowns, claims and customer information together.</p></div><div className="score-hero"><span>Source workbooks</span><strong>4</strong><small>Imported for demo</small></div></div>
 <div className="flow-card"><div><b>01</b><strong>Existing data</strong><small>Excel · FDMS · PDFs · manual inputs</small></div><i>→</i><div><b>02</b><strong>Dealer Data Hub</strong><small>Structure · validate · preserve history</small></div><i>→</i><div><b>03</b><strong>Reports & intelligence</strong><small>Employee · incentive · workshop · claims</small></div><i>→</i><div><b>04</b><strong>Management action</strong><small>Find exceptions · follow up · decide</small></div></div>
 <div className="stats-grid"><Metric label="Mechanic KRA" value="6" note="criteria · 1–5 scale"/><Metric label="Monthly KRA" value={monthly.toFixed(2)} note="VISHWAJEET · June 2026 · derived"/><Metric label="Report domains" value="4" note="Workshop · Breakdown · FML · Customer"/><Metric label="Source workbooks" value="4" note="Current static demo"/></div>
 <div className="two-col"><Card><Head title="01 · Employee Intelligence" sub="Preserve the existing evaluation process, then add objective intelligence." tag="PRIORITY"/><div className="feature-list"><div><b>Evaluation</b><span>Exact six Mechanic KRA fields</span><Badge>SOURCE</Badge></div><div><b>Monthly history</b><span>Weekly score → monthly average</span><Badge tone="derived">DERIVED</Badge></div><div><b>Performance layer</b><span>Objective KPIs when attribution exists</span><Badge tone="proposed">PROPOSED</Badge></div></div><button className="primary wide" onClick={()=>setView("employee")}>Open Employee Intelligence →</button></Card><Card><Head title="02 · Data & Reports" sub="The end of manually opening separate files to answer one question." tag="PRIORITY"/><div className="feature-list"><div><b>Workshop / Job Card</b><span>Customer · vehicle · parts · labour · invoice</span><Badge>SOURCE</Badge></div><div><b>Breakdown</b><span>Complaint · days open · supervisor · parts</span><Badge>SOURCE</Badge></div><div><b>FML / Claims</b><span>Status · passed · rejected · payment</span><Badge>SOURCE</Badge></div></div><button className="primary wide" onClick={()=>setView("reports")}>Open Data & Reports →</button></Card></div>
 </>}

function DataHub(){return <><div className="page-intro"><div><Badge>DATA HUB</Badge><h2>Every report becomes a traceable data source.</h2><p>The demo shows the information layer, not a replacement for Force FDMS or Zoho.</p></div><div className="score-hero"><span>Sources</span><strong>4</strong><small>Imported</small></div></div><Card><Head title="Existing reporting ecosystem" sub="The source files currently maintained by the dealership." tag="SOURCE"/><div className="source-grid">{sources.map(s=><div className="source-card" key={s[0]}><div className="source-icon">X</div><div><b>{s[0]}</b><span>{s[1]}</span><small>{s[2]}</small></div><Badge>IMPORTED</Badge></div>)}</div></Card><div className="stats-grid"><Metric label="Field mapping" value="Preview" note="Source → system fields"/><Metric label="Duplicate detection" value="Preview" note="Record checks"/><Metric label="Missing data" value="Preview" note="Required field review"/><Metric label="Traceability" value="On" note="Source remains visible"/></div><Card><Head title="How the data becomes useful" sub="One structured layer feeding multiple reports." tag="PROPOSED ARCHITECTURE"/><div className="big-flow"><div><b>Source files</b><small>Workshop · KPI · Breakdown · FML</small></div><i>→</i><div><b>Structured records</b><small>Mapped & validated</small></div><i>→</i><div><b>Dealer reports</b><small>Search · filter · history</small></div><i>→</i><div><b>Intelligence</b><small>Performance · incentive · action</small></div></div></Card></>}

function Employee({tab,setTab,week,setWeek,monthly}:{tab:"evaluation"|"history"|"performance";setTab:(t:"evaluation"|"history"|"performance")=>void;week:number;setWeek:(n:number)=>void;monthly:number}){const score=weekly[week-1];return <><div className="page-intro"><div><Badge>EMPLOYEE INTELLIGENCE</Badge><h2>VISHWAJEET</h2><p>Mechanic · June 2026 · source-backed evaluation</p></div><div className="score-hero"><span>Average for month</span><strong>{monthly.toFixed(2)}</strong><small>/ 5 · derived</small></div></div><div className="tabs"><button className={tab==="evaluation"?"active":""} onClick={()=>setTab("evaluation")}>KRA Assessment</button><button className={tab==="history"?"active":""} onClick={()=>setTab("history")}>Monthly History</button><button className={tab==="performance"?"active":""} onClick={()=>setTab("performance")}>Performance <Badge tone="proposed">PROPOSED</Badge></button></div>{tab==="evaluation"&&<Card><Head title="Weekly KRA Assessment" sub="Exact Mechanic fields from June 26.xlsx. Six scores are equally averaged." tag="SOURCE"/><div className="week-tabs">{[1,2,3,4].map(w=><button className={week===w?"active":""} onClick={()=>setWeek(w)} key={w}>Week {w}</button>)}</div><Table headers={["KRA / Criteria","Score","Rating"]} rows={kras.map(([n,v])=>[n,String(v[week-1]),["Very Bad","Poor","Pass","Good","Excellent"][v[week-1]-1]])}/><div className="score-strip"><div><span>Week {week} Final Score</span><b>{score.toFixed(6)}</b><small>SUM of six scores ÷ 6</small></div><div><span>Average for month</span><b>{monthly.toFixed(6)}</b><small>Average of weekly Final Scores</small></div></div></Card>}{tab==="history"&&<Card><Head title="June 2026 weekly history" sub="Derived from the weekly KRA assessments." tag="DERIVED"/><div className="week-grid">{weekly.map((s,i)=><button className={`week-card ${week===i+1?"selected":""}`} onClick={()=>setWeek(i+1)} key={i}><span>Week {i+1}</span><strong>{s.toFixed(2)}</strong><small>{kras.reduce((a,k)=>a+k[1][i],0)} / 30 points</small></button>)}</div></Card>}{tab==="performance"&&<><div className="proposed-card"><div><Badge tone="proposed">PROPOSED</Badge><h3>Objective performance layer</h3><p>The current source has KRA assessment and workshop records, but does not establish reliable technician-to-job attribution. The demo therefore shows the future layer without inventing values.</p></div><div className="proposed-metrics"><span>Technician Productivity<b>—</b></span><span>Average TAT<b>—</b></span><span>Repeat / Rework<b>—</b></span><span>Labour Generated<b>—</b></span></div></div></>}</>}

function Incentive(){return <><div className="page-intro"><div><Badge>INCENTIVE INTELLIGENCE</Badge><h2>Existing incentive policy, made reviewable.</h2><p>Policy values below are reproduced from the supplied Incentive sheet.</p></div></div><Card><Head title="Mechanic / Electrician" sub="Existing incentive basis and assessment multiplier." tag="SOURCE"/><div className="formula"><b>10% of (Total Labour generated without GST − (Salary + OT))</b></div><div className="multiplier-grid">{[[1,"0.50"],[2,"0.65"],[3,"0.80"],[4,"1.00"],[5,"1.20"]].map(x=><div key={x[0]}><span>Assessment {x[0]}</span><strong>{x[1]}</strong><small>Multiplier</small></div>)}</div></Card><div className="two-col"><Card><Head title="Floor Advisors" tag="SOURCE"/><Table headers={["Target","Monthly Labour","Quarterly Labour","Quarterly Incentive"]} rows={[["T1","₹225,000","₹675,000","₹3,000"],["T2","₹275,000","₹825,000","₹6,000"],["T3","₹325,000","₹975,000","₹9,000"],["T4","₹375,000","₹1,125,000","₹16,000"]]}/></Card><Card><Head title="CRE — Srishti" tag="SOURCE"/><Table headers={["Monthly","Quarterly","Quarterly Incentive"]} rows={[["440","1320","₹3,000"],["465","1395","₹6,000"],["490","1470","₹9,000"],["515","1545","₹12,000"]]}/></Card></div><Card><Head title="Calculation preview" sub="No amount is fabricated without employee-linked labour and salary/OT data." tag="PROPOSED UI"/><div className="calc-grid">{[["Employee","VISHWAJEET"],["Average Points","3.83 / 5"],["Assessment","4"],["Multiplier","1.00"],["Labour Generated","—"],["Eligible Incentive","Pending data"]].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div></Card></>}

function Reports({report,setReport}:{report:Report;setReport:(r:Report)=>void}){const cfg={workshop:{title:"Workshop / Job Card",sub:"Customer, vehicle, service, parts, labour and invoice information.",headers:["Job Card No","Customer Name","Phone","Vehicle","Model","Service","Part Value","Labour","Invoice"],rows:workshop,source:"Gazipur workshop reporting Jul 26.xlsx · Job Card"},breakdown:{title:"Breakdown Tracking",sub:"Open/closed cases, complaint, response, supervisor and parts.",headers:["Complain No","Vehicle","Customer","Complaint","Days Open","Status","Supervisor"],rows:breakdown,source:"Breakdown tracking.xlsx · Daily service Tracker"},claims:{title:"FML / Claims",sub:"Claim status, invoice value, passed/rejected amount and payment.",headers:["Claim Invoice","Internal No","Invoice Date","Invoice Value","Type","Status","Passed","Rejected","Payment"],rows:claims,source:"AMIT UPDATED FML Claim Sheet Feb 26.xlsx · Data Report sheet"},customer:{title:"Customer / Vehicle",sub:"Customer and vehicle fields available in imported Job Card data.",headers:["Customer","Phone","Vehicle","Model","Category","Service","Job Card","Invoice","Total"],rows:[["Lachchiram PG College Salikpur Gzp","9454277263","UP61AT2335","T1","School","Paid","91","—","₹646"],["Samta Pb School","9454277363","UP61AT0416","T1","School","Paid","92","—","₹2,225"]],source:"Gazipur workshop reporting Jul 26.xlsx · Job Card"}}[report];return <><div className="page-intro"><div><Badge>DATA & REPORTS</Badge><h2>{cfg.title}</h2><p>{cfg.sub}</p></div></div><div className="report-tabs">{([['workshop','Workshop / Job Card'],['breakdown','Breakdown'],['claims','FML / Claims'],['customer','Customer / Vehicle']] as [Report,string][]).map(x=><button className={report===x[0]?"active":""} onClick={()=>setReport(x[0])} key={x[0]}>{x[1]}</button>)}</div><Card><Head title={cfg.title} sub={cfg.source} tag="SOURCE DATA"/><div className="table-toolbar"><input placeholder="Search source records..."/><button>June 2026⌄</button><button>Export preview</button></div><Table headers={cfg.headers} rows={cfg.rows}/><div className="field-note"><Badge tone="derived">TRACEABLE</Badge>Source terminology is preserved. Production version can add validation, historical search and derived management reports on top.</div></Card></>}
